namespace Advanced
{
    class Program
    {
        static void Main(string[] args)
        {
            //StacksAndQueues.BasicStackOperations.Execute();
            //StacksAndQueues.BasicQueueOperations.Execute();
            //StacksAndQueues.MaximumAndMinimumElement.Execute();
            //StacksAndQueues.FastFood.Execute();
            //StacksAndQueues.FashionBoutique.Execute();
            //StacksAndQueues.AutoRepairAndService.Execute();
            //StacksAndQueues.TruckTour.Execute();
            //MultidimensionalArrays.DiagonalDifference.Execute();
            //MultidimensionalArrays.TwoByTwoSquaresInMatrix.Execute();
            //MultidimensionalArrays.MaximalSum.Execute();
            //MultidimensionalArrays.MatrixShuffling.Execute();
            //MultidimensionalArrays.SnakeMoves.Execute();
            //MultidimensionalArrays.BombTheBasement.Execute();
            //MultidimensionalArrays.KnightGame.Execute();
            //MultidimensionalArrays.Miner.Execute();
            //SetsAndDictionaries.CountSameValuesInArray.Execute();
            //SetsAndDictionaries.AverageStudentGrades.Execute();
            //SetsAndDictionaries.ProductShop.Execute();
            //SetsAndDictionaries.CitiesByContinentAndCountry.Execute();
            //SetsAndDictionaries.RecordUniqueNames.Execute();
            //SetsAndDictionaries.ParkingLot.Execute();
            //SetsAndDictionaries.SoftUniParty.Execute();
            //SetsAndDictionaries.UniqueUsernames.Execute();
            //SetsAndDictionaries.SetsOfElements.Execute();
            //SetsAndDictionaries.PeriodicTable.Execute();
            //SetsAndDictionaries.EvenTimes.Execute();
            //SetsAndDictionaries.CountSymbols.Execute();
            //SetsAndDictionaries.Wardrobe.Execute();
            //SetsAndDictionaries.TheVLogger.Execute();
            //FilesAndDirectories.OddLines.OddLines.Execute();
            //FilesAndDirectories.LineNumbers.LineNumbers.Execute();
            FilesAndDirectories.WordCount.WordCount.Execute();
        }
    }
}
